### ISSUE TITLE
Generate paths using node "path" module

### ISSUE THREAD

**Issue by shuantsu-zz** [Tserewara/pywebpack#1]
In this file:
[https://github.com/Tserewara/pywebpack/blob/master/boilerplates/conf.json.ini](https://github.com/Tserewara/pywebpack/blob/master/boilerplates/conf.json.ini)

On the top we can se the output file using the `path` node module to resolve the path to the file.

    { plugins: [new MiniCssExtractPlugin({
        filename: 'css/[name].bundle.css'
      })],
      output: {
        filename: 'js/[name].bundle.js',
        path: path.join(__dirname, "{blueprint_relative_path}/{blueprint_name}_static/assets"),
      },
       optimization: {
         splitChunks: {
           chunks: 'all',
         },
       }, 

But in the `index` and the `module` properties of the object the path is resolved with python. This can lead to inconsistencies when bringing files from the git repo.

    entry: {
               index: [
               '{blueprint_abs_path}/{blueprint_name}_static/src/js/index.js',
               '{blueprint_abs_path}/{blueprint_name}_static/src/scss/index.scss'
               ]

    options: {
                  publicPath: "{blueprint_abs_path}/{blueprint_name}_static/assets/css",
                },

The rendered file:

    output: {
        filename: 'js/bundle.js',
        path: path.join(__dirname, "app/bp_one/static_bp_one/assets"),

    entry: {
               index: [
               'C:/Users/shuan/Dropbox/GITHUB/teste_flask/app/bp_one/static_bp_one/src/js/index.js',

It would be better if the `path` node module were used on all occurrences

**Comment by Tserewara** [comment]
Done
